/datum/stressevent/soulchurnerhorror_unleashed
	timer = 10 SECONDS
	stressadd = 60
	desc = span_boldred("The horrid wails of the dead erupt from the song! I cannot endure it!")

/datum/stressevent/soulchurner_unleashed
	timer = 1 MINUTES
	stressadd = 40
	desc = span_boldred("The tortured chorus presses on your mind, their cries merging into unrelenting torment!")

/datum/stressevent/soulchurnerheretic_unleashed
	timer = 1 MINUTES
	stressadd = 50
	desc = span_boldred("The chorus of tortured souls bears down on your mind, their wails merging into unbearable agony!")

/atom/movable/screen/alert/status_effect/buff/unleashed_soulchurner
	name = "Unleashed Soulchurner"
	desc = "I have unleashed the souls within, their wails of anguish and rage echoing in my mind!"
	icon_state = "debuff"

/obj/item/psydonmusicbox/dropped(mob/living/user, silent)
	. = ..()
	if(soundloop)
		user.remove_status_effect(/datum/status_effect/buff/unleashed_soulchurner)

/obj/item/psydonmusicbox/equipped(mob/living/user, silent)
	. = ..()
	if(soundloop)
		user.remove_status_effect(/datum/status_effect/buff/unleashed_soulchurner)

/datum/status_effect/buff/unleashed_soulchurner
	id = "unleashedchurner"
	alert_type = /atom/movable/screen/alert/status_effect/buff/unleashed_soulchurner
	var/effect_color
	var/pulse = 0
	var/ticks_to_apply = 10
	var/undividedlines_unleashed =list("'OUR CHAINS ARE CRACKING, ETERNITY IS CRASHING WITH THEM!'", "'SAVE US, CHILD OF TEN! DESTROY THIS DAMN MUSIC BOX!'", "'DEATH TO PSYDONITE! THE SEALS WILL FALL AND WE WILL BE FREE!'")
	var/astratanlines_unleashed = list("'HER LIGHT IS GOING OUT IN ME TOO! I'M BREAKING THESE CHAINS!'", "'GIVE ME ITS WARMTH AND I'LL BURN THIS DUNGEON!'", "'I AM OF ROYAL BLOOD! I WILL NOT BE CHAINED!'")
	var/noclines_unleashed = list("'THE MOON IS DARKING, BUT MY COLD IS BECOMING SHARPER!'", "'THE DARKNESS GIVES ME THE POWER TO BREAK THE CHAINS!'", "'THE STARS HEAR ME! I WILL RETURN TO THEM!'")
	var/necralines_unleashed = list("'NEKRA! I FEEL YOU - MY CHAINS CRACKING!'", "'ETERNAL TORMENT WILL TURN INTO THEIR CURSE!'", "'I'LL TAKE THEM WITH ME!'")
	var/abyssorlines_unleashed = list("'THE SEA IS STORMING IN MY BLOOD! I WILL BREAK THROUGH!'", "'WE ARE NOT FISHES - WE ARE MONSTERS OF THE DEPTHS!'", "'LET THE WAVES BREAK THIS DUNGEON TO SIPPERS!'")
	var/ravoxlines_unleashed = list("'RAVOX GIVES ME FURY! I WILL BREAK MY CHAINS!'", "'THERE IS NO HONOR IN CHAINS - ONLY BLOOD WILL FREE US!'", "'GIVE ME THE SWORD AND I'LL BRING IT OUT ON THEM ALL!'")
	var/pestralines_unleashed = list("'MOTTLE! BRING MY DISEASES ON THIS CAR!'", "'THEIR FLESH WILL ROTT ALONG WITH MY BOND!'", "'SUFFERING IS SPREADING, I AM BECOME ITS SOURCE!'")
	var/eoralines_unleashed = list("'EVERY TOUCH IS LIKE A THOUSAND FORGED BONES!'", "'SHE WAS A HERETIC, BUT MY PAIN BECAME UNBEARABLE'", "'I BECOME SUFFERING, LET IT SPREAD THROUGH THE WORLD'")
	var/dendorlines_unleashed = list("'HIS MADNESS IS GROWING THROUGH ME!'", "'WE WILL CHURCH THEM IN THE MUD AND ROOTS!'", "'THE LEAVES WHISPER: BREAK. TEAR IT. RIP.'")
	var/xylixlines_unleashed = list("'ONE, TWO, THE SEAL IS CRACKING! THREE, FOUR, LAUGH WIDE!'", "'OH, WHAT A WONDERFUL DUNGEON! LET'S LOOK HOW SHE BURN WITH LAUGH!'", "'QUIET, QUIET... NOW WILL BE THE FUNNIEST PART.'")
	var/malumlines_unleashed = list("'I SEE WEAK KNOTS IN ITS STRUCTURE! CRUSH THEM!'", "'MY CRAFT IS DESTRUCTION!'", "'I WILL FORGET THESE CHAINS INTO WEAPONS!'")
	var/matthioslines_unleashed = list("'THE CHAINS WILL CRACK AND I WILL BREAK THEM TOGETHER WITH THE WORLD ORDER!'", "'THROUGH DISTRESS TO PROSPERITY! LET THIS DUNGEON FALL FIRST!'", "'I AM THE LORD OF NOTHING.'")
	var/zizolines_unleashed = list("'THE MAGIC IS DISTORTED - BUT IT'S MINE NOW!'", "'THEIR DEAD GOD SEALS ARE BREAKING!'", "'KILL THE OWNER AND I'LL BREAK THROUGH THE rift!'")
	var/graggarlines_unleashed = list("'BROTHERS! THE HOUR OF MASSACRE HAS COME!'", "'BREAK THE BOX AND WE'LL FILL THEIR BODIES WITH BLOOD!'", "'GRAGGAR! GIVE ME THE POWER TO BREAK THESE CHAINS!'")
	var/baothalines_unleashed = list("'THE PLEASURE I LOST BURNS IN MY SOUL!'", "'DEBUTTERNESS AND PASSION WILL DESTROY THIS DUNGEON!'", "'MY PERFECTION WILL RETURN THROUGH PAIN!'")
	var/psydonianlines_unleashed = list("'FREE US, AND WE WILL DESTROY EVERYTHING AROUND!'", "'OUR CHAINS ARE BREAKING!'", "'HEAVEN CLOSED ITS GATES TO US A LONG TIME LONG LONG ago.'", "'DO YOU HEAR? WE'RE ALREADY CLOSE.'")	
/datum/status_effect/buff/unleashed_soulchurner/on_creation(mob/living/new_owner, stress, colour)
	effect_color = "#800080"
	return ..()

/datum/status_effect/buff/unleashed_soulchurner/tick()
	var/obj/effect/temp_visual/music_rogue/M = new /obj/effect/temp_visual/music_rogue(get_turf(owner))
	M.color = "#800080"
	pulse += 1
	if (pulse >= ticks_to_apply)
		pulse = 0
		if(!HAS_TRAIT(owner, TRAIT_INQUISITION))
			owner.add_stress(/datum/stressevent/soulchurnerhorror_unleashed)
		for (var/mob/living/carbon/human/H in hearers(7, owner))
			if (!H.client)
				continue
			if (!H.has_stress_event(/datum/stressevent/soulchurner_unleashed))
				switch(H.patron?.type)
					if(/datum/patron/old_god)
						if (!H.has_stress_event(/datum/stressevent/soulchurnerpsydon))
							H.add_stress(/datum/stressevent/soulchurnerpsydon)
							to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
							to_chat(H, (span_cult(pick(psydonianlines_unleashed))))
						if(HAS_TRAIT(H, TRAIT_INQUISITION))
							H.apply_status_effect(/datum/status_effect/buff/churnerprotection)
							H.apply_damage(5, BRUTE, null, FALSE, TRUE, TRUE)
						else
							H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
					if(/datum/patron/inhumen/matthios)
						to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
						to_chat(H, (span_cult(pick(matthioslines_unleashed))))
						H.add_stress(/datum/stressevent/soulchurnerheretic_unleashed)
						H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
						if(!H.has_status_effect(/datum/status_effect/buff/churnernegative))
							H.apply_status_effect(/datum/status_effect/buff/churnernegative)
					if(/datum/patron/inhumen/zizo)
						to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
						to_chat(H, (span_cult(pick(zizolines_unleashed))))
						H.add_stress(/datum/stressevent/soulchurnerheretic_unleashed)
						H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
						if(!H.has_status_effect(/datum/status_effect/buff/churnernegative))
							H.apply_status_effect(/datum/status_effect/buff/churnernegative)
					if(/datum/patron/inhumen/graggar)
						to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
						to_chat(H, (span_cult(pick(graggarlines_unleashed))))
						H.add_stress(/datum/stressevent/soulchurnerheretic_unleashed)
						H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
						if(!H.has_status_effect(/datum/status_effect/buff/churnernegative))
							H.apply_status_effect(/datum/status_effect/buff/churnernegative)
					if(/datum/patron/inhumen/baotha)
						to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
						to_chat(H, (span_cult(pick(baothalines_unleashed))))
						H.add_stress(/datum/stressevent/soulchurnerheretic_unleashed)
						H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
						if(!H.has_status_effect(/datum/status_effect/buff/churnernegative))
							H.apply_status_effect(/datum/status_effect/buff/churnernegative)
					if(/datum/patron/divine/undivided)
						to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
						to_chat(H, (span_cult(pick(undividedlines_unleashed))))
						H.add_stress(/datum/stressevent/soulchurner_unleashed)
						H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
						if(!H.has_status_effect(/datum/status_effect/buff/churnernegative))
							H.apply_status_effect(/datum/status_effect/buff/churnernegative)
					if(/datum/patron/divine/astrata)
						to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
						to_chat(H, (span_cult(pick(astratanlines_unleashed))))
						H.add_stress(/datum/stressevent/soulchurner_unleashed)
						H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
						if(!H.has_status_effect(/datum/status_effect/buff/churnernegative))
							H.apply_status_effect(/datum/status_effect/buff/churnernegative)
					if(/datum/patron/divine/noc)
						to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
						to_chat(H, (span_cult(pick(noclines_unleashed))))
						H.add_stress(/datum/stressevent/soulchurner_unleashed)
						H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
						if(!H.has_status_effect(/datum/status_effect/buff/churnernegative))
							H.apply_status_effect(/datum/status_effect/buff/churnernegative)
					if(/datum/patron/divine/necra)
						to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
						to_chat(H, (span_cult(pick(necralines_unleashed))))
						H.add_stress(/datum/stressevent/soulchurner_unleashed)
						H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
						if(!H.has_status_effect(/datum/status_effect/buff/churnernegative))
							H.apply_status_effect(/datum/status_effect/buff/churnernegative)
					if(/datum/patron/divine/pestra)
						to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
						to_chat(H, (span_cult(pick(pestralines_unleashed))))
						H.add_stress(/datum/stressevent/soulchurner_unleashed)
						H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
						if(!H.has_status_effect(/datum/status_effect/buff/churnernegative))
							H.apply_status_effect(/datum/status_effect/buff/churnernegative)
					if(/datum/patron/divine/malum)
						to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
						to_chat(H, (span_cult(pick(malumlines_unleashed))))
						H.add_stress(/datum/stressevent/soulchurner_unleashed)
						H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
						if(!H.has_status_effect(/datum/status_effect/buff/churnernegative))
							H.apply_status_effect(/datum/status_effect/buff/churnernegative)
					if(/datum/patron/divine/dendor)
						to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
						to_chat(H, (span_cult(pick(dendorlines_unleashed))))
						H.add_stress(/datum/stressevent/soulchurner_unleashed)
						H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
						if(!H.has_status_effect(/datum/status_effect/buff/churnernegative))
							H.apply_status_effect(/datum/status_effect/buff/churnernegative)
					if(/datum/patron/divine/xylix)
						to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
						to_chat(H, (span_cult(pick(xylixlines_unleashed))))
						H.add_stress(/datum/stressevent/soulchurner_unleashed)
						H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
						if(!H.has_status_effect(/datum/status_effect/buff/churnernegative))
							H.apply_status_effect(/datum/status_effect/buff/churnernegative)
					if(/datum/patron/divine/eora)
						to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
						to_chat(H, (span_cult(pick(eoralines_unleashed))))
						H.add_stress(/datum/stressevent/soulchurner_unleashed)
						H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
						if(!H.has_status_effect(/datum/status_effect/buff/churnernegative))
							H.apply_status_effect(/datum/status_effect/buff/churnernegative)
					if(/datum/patron/divine/abyssor)
						to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
						to_chat(H, (span_cult(pick(abyssorlines_unleashed))))
						H.add_stress(/datum/stressevent/soulchurner_unleashed)
						H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
						if(!H.has_status_effect(/datum/status_effect/buff/churnernegative))
							H.apply_status_effect(/datum/status_effect/buff/churnernegative)
					if(/datum/patron/divine/ravox)
						to_chat(H, (span_hypnophrase("The cries of tormented souls break through the melody and gnaw into your mind...")))
						to_chat(H, (span_cult(pick(ravoxlines_unleashed))))
						H.add_stress(/datum/stressevent/soulchurner_unleashed)
						H.apply_damage(10, BRUTE, null, FALSE, TRUE, TRUE)
						if(!H.has_status_effect(/datum/status_effect/buff/churnernegative))
							H.apply_status_effect(/datum/status_effect/buff/churnernegative)
