/datum/asset/simple/roguefonts
	keep_local_name = TRUE
	assets = list(
		"Mookmania.otf" = 'interface/fonts/Mookmania.otf', //Primary
		"pterra.ttf" = 'interface/fonts/pterra.ttf',
		"lora-regular.ttf" = 'interface/fonts/lora-regular.ttf',
		"lora-italic.ttf" = 'interface/fonts/lora-italic.ttf',
		"lora-bold.ttf" = 'interface/fonts/lora-bold.ttf',
		"lora-medium.ttf" = 'interface/fonts/lora-medium.ttf',
		"medievalsharp.ttf" = 'interface/fonts/medievalsharp.ttf',
		"newrocker.ttf" = 'interface/fonts/newrocker.ttf',
		"nosfer.ttf" = 'interface/fonts/nosfer.ttf',
		"chiseld.ttf" = 'interface/fonts/chiseld.ttf',
		"blackmoor.ttf" = 'interface/fonts/blackmoor.ttf',
		"handwrite.ttf" = 'interface/fonts/handwrite.ttf',
		"book1.ttf" = 'interface/fonts/book1.ttf',
		"book2.ttf" = 'interface/fonts/book1.ttf',
		"book3.ttf" = 'interface/fonts/book1.ttf',
		"book4.ttf" = 'interface/fonts/book1.ttf',
		"Celtes SP.otf" = 'interface/fonts/languages/Celtes SP.otf', //Dwarves Doesn't work
		"MarkScript-Regular.ttf" = 'interface/fonts/languages/MarkScript-Regular.ttf', //Elvish
		"Comforter Brush.otf" = 'interface/fonts/languages/Comforter Brush.otf', //infernal
		"VizaviTYGRA.ttf" = 'interface/fonts/languages/VizaviTYGRA.ttf', //Orc
		"Kamelia.ttf" = 'interface/fonts/languages/Kamelia.ttf', //aasimar and samaglos
		"FDMedian.ttf" = 'interface/fonts/languages/FDMedian.ttf', //underad
		"Kautiva Cyrillic Black.ttf" = 'interface/fonts/languages/Kautiva Cyrillic Black.ttf', //Lizard
		"ALOT Gutenberg B Normal.ttf" = 'interface/fonts/languages/ALOT Gutenberg B Normal.ttf', //Grenzel
		"gyedzai.otf" = 'interface/fonts/languages/gyedzai.otf', //China
		"valorian.ttf" = 'interface/fonts/languages/valorian.ttf', //Valoria
		"Ganesha Type.ttf" = 'interface/fonts/languages/Ganesha Type.ttf', //Kazengunsky Doesn't work
		"lingyuese.ttf" = 'interface/fonts/languages/lingyuese.ttf',
		"otavan.ttf" = 'interface/fonts/languages/otavan.ttf',
		"oldazure.ttf" = 'interface/fonts/languages/oldazure.ttf',
		"undercommon.ttf" = 'interface/fonts/languages/undercommon.ttf',
		"etruscan.ttf" = 'interface/fonts/languages/etruscan.ttf',
		"gronnic.ttf" = 'interface/fonts/languages/gronnic.ttf',
		"aavnic.ttf" = 'interface/fonts/languages/aavnic.ttf',
		"parisienne.ttf" = 'interface/fonts/tegaki/parisienne.ttf',
		"parisienne_data.json" = 'interface/fonts/tegaki/parisienne_data.json',
		"Deutsch Gothic.ttf" = 'interface/fonts/languages/Deutsch Gothic.ttf', //Otava
		"TolkienCyr.ttf" = 'interface/fonts/languages/TolkienCyr.ttf', //Etruscan
		"RUSNeverwinter.ttf" = 'interface/fonts/languages/RUSNeverwinter.ttf', //Gronnovsky
		"Arabic Cyr (kerning fixed).ttf" = 'interface/fonts/languages/Arabic Cyr (kerning fixed).ttf', //Aaviansky Doesn't work
	)
